name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout nwdrone
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up build environment
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0

      - name: Build
        run: zig build -Dplatform=rpi0 --release=any --summary all

      - name: Upload zig-out
        uses: actions/upload-artifact@v4
        with:
          name: zig-out
          path: ${{github.workspace}}/zig-out
