name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout nwdrone
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Zig environment
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0

      - name: Enable Corepack
        run: corepack enable
      
      - name: Check cache
        uses: Hanaasagi/zig-action-cache@master
        with:
          cache-on-failure: true

      - name: Build
        run: zig build -Dplatform=rpi0 -Dstrip=true -j1 --release=any --summary all

      - name: Test
        run: zig build test --summary all

      - name: Upload zig-out
        uses: actions/upload-artifact@v4
        with:
          name: zig-out
          path: ${{github.workspace}}/zig-out
